# Generated by Django 3.2.5 on 2021-07-02 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20210702_1159'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alabala',
        ),
    ]
