# Generated by Django 3.2.5 on 2021-07-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_alter_topshiriq_ilova'),
    ]

    operations = [
        migrations.AddField(
            model_name='topshiriq',
            name='topshiriq_raqami',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
