# Generated by Django 3.2.5 on 2021-07-05 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_alter_topshiriq_ilova'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topshiriq',
            name='ilova',
            field=models.FileField(null=True, upload_to='Ilovalar'),
        ),
    ]
