# Generated by Django 3.2.5 on 2021-07-05 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_remove_topshiriq_topshiriq_raqami'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topshiriq',
            name='ilova',
            field=models.FileField(blank=True, null=True, upload_to='Ilovalar'),
        ),
    ]
